# Generated by Django 4.1.1 on 2022-09-23 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('packagename', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RPayment',
            fields=[
                ('payment_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('mode', models.CharField(max_length=25)),
                ('ruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.ruser')),
            ],
        ),
        migrations.CreateModel(
            name='RBooking',
            fields=[
                ('booking_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('departure_date', models.DateField()),
                ('no_of_people', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField()),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.packagedetails')),
                ('ruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.ruser')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=200)),
                ('ruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.ruser')),
            ],
        ),
    ]
