# Generated by Django 4.1.1 on 2022-09-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='addfeedback',
        ),
        migrations.RenameField(
            model_name='addfeedback',
            old_name='feedback',
            new_name='addfeedback',
        ),
    ]
